[package]
name = "rattai"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = { version = "0.17.3", optional = true }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
whisper-rs = { version = "0.16.0", optional = true }

[features]
whisper = ["dep:whisper-rs"]
piper = ["dep:cpal"]
#parakeet = []
